// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvgtmfmvisxhivmldrhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Z3RtZm12aXN4aGl2bWxkcmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODUwNzYsImV4cCI6MjA3MjE2MTA3Nn0.fw3TtYzM92-hV-BAN2PeA1NnGLa6TvhvEhgjqQ1QdCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});